version: "3"

services:
    php-fpm:
        image: softyfire/php:7.2-fpm
        volumes:
            - ${PWD}/app:/app

    nginx:
        image: nginx:latest
        links:
            - php-fpm
        ports:
            - 2080:80
        volumes:
            - ${PWD}/app:/app
            - ${PWD}/config/vhost.conf:/etc/nginx/conf.d/default.conf

    mysql:
        image: mysql:5.7
        volumes:
            - ${PWD}/data/mysql:/var/lib/mysql
        environment:
            - MYSQL_DATABASE=test
            - "MYSQL_USER=${MYSQL_USER}"
            - "MYSQL_PASSWORD=${MYSQL_PASSWORD}"
            - MYSQL_RANDOM_ROOT_PASSWORD=1
